validator: xml: add an idempotent CharsetReader
The CharsetReader does not do anything, but it avoids the library
complaining when handling an UTF-16 file.

Added test files as regression tests. Without the change the error manifests as:

> test/fixtures/good-utf16.xml
> error: xml: encoding "utf-16" declared but Decoder.CharsetReader is nil